
version: '3.7'
services:
  worker_postgres_tpch_1_4_7:
    image: hoeunlee228/worker:latest
    container_name: worker_postgres_tpch_1_4_7
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db_postgres_tpch_1_4_7
      - DB_PORT=5432
      - DB_NAME=tpch
      - DB_USER=postgres
      - DB_PASS=postgres
      - BENCHMARK=tpch
      - QUERY_START=1
      - QUERY_END=4
      - REPEAT_COUNT=50
      - RESULT_CSV=/mnt/results/batch_7.csv
      - RESULT_LOG=/mnt/results/batch_7.log
    volumes:
      - ./results:/mnt/results
    deploy:
      resources:
        limits:
          cpus: "6"
    depends_on:
      - db_postgres_tpch_1_4_7

  db_postgres_tpch_1_4_7:
    image: hoeunlee228/postgres-tpch:latest
    container_name: db_postgres_tpch_1_4_7
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Dlghdms0228
    