
version: '3.7'
services:
  worker_mssql_tpch_21_22_3:
    image: hoeunlee228/worker:latest
    container_name: worker_mssql_tpch_21_22_3
    environment:
      - DB_TYPE=mssql
      - DB_HOST=db_mssql_tpch_21_22_3
      - DB_PORT=1433
      - DB_NAME=tpch
      - DB_USER=SA
      - DB_PASS=Dlghdms0228
      - BENCHMARK=tpch
      - QUERY_START=21
      - QUERY_END=22
      - REPEAT_COUNT=1
      - RESULT_CSV=/mnt/results/batch_3.csv
      - RESULT_LOG=/mnt/results/batch_3.log
    volumes:
      - ./results:/mnt/results
    deploy:
      resources:
        limits:
          cpus: "8"
    depends_on:
      - db_mssql_tpch_21_22_3

  db_mssql_tpch_21_22_3:
    image: hoeunlee228/mssql-tpch:latest
    container_name: db_mssql_tpch_21_22_3
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Dlghdms0228
    