
version: '3.7'
services:
  worker_mssql_tpch_7_8_4:
    image: hoeunlee228/worker:latest
    container_name: worker_mssql_tpch_7_8_4
    environment:
      - DB_TYPE=mssql
      - DB_HOST=db_mssql_tpch_7_8_4
      - DB_PORT=1433
      - DB_NAME=tpch
      - DB_USER=SA
      - DB_PASS=Dlghdms0228
      - BENCHMARK=tpch
      - QUERY_START=7
      - QUERY_END=8
      - REPEAT_COUNT=1
      - RESULT_CSV=/mnt/results/batch_4.csv
      - RESULT_LOG=/mnt/results/batch_4.log
    volumes:
      - ./results:/mnt/results
    depends_on:
      - db_mssql_tpch_7_8_4

  db_mssql_tpch_7_8_4:
    image: hoeunlee228/mssql-tpch:latest
    container_name: db_mssql_tpch_7_8_4
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Dlghdms0228
    cpus: "8"
    